{"name": "test_verify_the_schedule_call_back", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\n  - navigating to \"https://mqa2.xavlab.xyz/\", waiting until \"load\"", "trace": "page_fixture = <Page url='https://mqa2.xavlab.xyz/'>\n\n    @pytest.mark.usefixtures(\"page_fixture\")\n    def test_verify_the_schedule_call_back(page_fixture):\n        \"\"\"\n        Test to verify the 'Schedule Call Back' feature.\n        \"\"\"\n    \n        # Fetch test data\n        test_data = get_test_data()\n        username = test_data[\"valid_user\"][\"username\"]\n        password = test_data[\"valid_user\"][\"password\"]\n        domain = test_data[\"valid_user\"][\"domain\"]\n    \n        # Use the page instance from page_fixture\n        page = page_fixture\n    \n        # Initialize all page objects using a single function\n        pages = initialize_page_objects(page)\n    \n        with allure.step(\"Navigating to Login Page\"):\n>           pages[\"login_page\"].navigateToURL()\n\ntest_Automated_Call_Back_Scheduling.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\pages\\login_page.py:21: in navigateToURL\n    self.page.goto(BASE_URL)\n..\\..\\venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:9006: in goto\n    self._sync(\n..\\..\\venv\\Lib\\site-packages\\playwright\\_impl\\_page.py:551: in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n..\\..\\venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py:145: in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n..\\..\\venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:61: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <playwright._impl._connection.Connection object at 0x00000269CC9D3CB0>\ncb = <function Channel.send.<locals>.<lambda> at 0x00000269CD1A5440>, is_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nE           Call log:\nE             - navigating to \"https://mqa2.xavlab.xyz/\", waiting until \"load\"\n\n..\\..\\venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:528: TimeoutError"}, "description": "\n    Test to verify the 'Schedule Call Back' feature.\n    ", "steps": [{"name": "Initializing Page Objects", "status": "passed", "start": 1741245918455, "stop": 1741245918482}, {"name": "Navigating to Login Page", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\n  - navigating to \"https://mqa2.xavlab.xyz/\", waiting until \"load\"\n\n", "trace": "  File \"C:\\Users\\puchha.pavan\\PycharmProjects\\PyTest_Python\\Fuel_iX_CX\\BA_UseCases\\test_Automated_Call_Back_Scheduling.py\", line 24, in test_verify_the_schedule_call_back\n    pages[\"login_page\"].navigateToURL()\n  File \"C:\\Users\\puchha.pavan\\PycharmProjects\\PyTest_Python\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\puchha.pavan\\PycharmProjects\\PyTest_Python\\Fuel_iX_CX\\pages\\login_page.py\", line 21, in navigateToURL\n    self.page.goto(BASE_URL)\n  File \"C:\\Users\\puchha.pavan\\PycharmProjects\\PyTest_Python\\venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9006, in goto\n    self._sync(\n  File \"C:\\Users\\puchha.pavan\\PycharmProjects\\PyTest_Python\\venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\puchha.pavan\\PycharmProjects\\PyTest_Python\\venv\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 551, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\puchha.pavan\\PycharmProjects\\PyTest_Python\\venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\Users\\puchha.pavan\\PycharmProjects\\PyTest_Python\\venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\puchha.pavan\\PycharmProjects\\PyTest_Python\\venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "steps": [{"name": "Navigating to the website", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\n  - navigating to \"https://mqa2.xavlab.xyz/\", waiting until \"load\"\n\n", "trace": "  File \"C:\\Users\\puchha.pavan\\PycharmProjects\\PyTest_Python\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\puchha.pavan\\PycharmProjects\\PyTest_Python\\Fuel_iX_CX\\pages\\login_page.py\", line 21, in navigateToURL\n    self.page.goto(BASE_URL)\n  File \"C:\\Users\\puchha.pavan\\PycharmProjects\\PyTest_Python\\venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9006, in goto\n    self._sync(\n  File \"C:\\Users\\puchha.pavan\\PycharmProjects\\PyTest_Python\\venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\puchha.pavan\\PycharmProjects\\PyTest_Python\\venv\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 551, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\puchha.pavan\\PycharmProjects\\PyTest_Python\\venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\Users\\puchha.pavan\\PycharmProjects\\PyTest_Python\\venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\puchha.pavan\\PycharmProjects\\PyTest_Python\\venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "start": 1741245918483, "stop": 1741245948507}], "start": 1741245918482, "stop": 1741245948510}], "attachments": [{"name": "test_verify_the_schedule_call_back - Failure Screenshot", "source": "933fb0a2-ee83-4caf-ab21-46bd54cd893d-attachment.png", "type": "image/png"}, {"name": "test_verify_the_schedule_call_back - Failure Trace", "source": "31a7643d-e2d2-45b9-abda-15c7101a21d2-attachment.txt", "type": "text/plain"}, {"name": "log", "source": "7c91322d-8d50-41a3-944a-f6c56fd3a33e-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "dce66120-c985-45bd-bd58-dd32dbc3554c-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "e6a00ccb-bf0b-4472-8191-1b6da2ae21c2-attachment.txt", "type": "text/plain"}], "start": 1741245918455, "stop": 1741245948516, "uuid": "9b6a394b-61cc-47fb-8a4f-d47127317517", "historyId": "06c87b8fec8480389e4abea6843d57f1", "testCaseId": "06c87b8fec8480389e4abea6843d57f1", "fullName": "test_Automated_Call_Back_Scheduling#test_verify_the_schedule_call_back", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('page_fixture')"}, {"name": "suite", "value": "test_Automated_Call_Back_Scheduling"}, {"name": "host", "value": "BA-000311899"}, {"name": "thread", "value": "6320-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_Automated_Call_Back_Scheduling"}]}